/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chcecbox;

import Estructura.Dni;
import Estructura.Persona;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pegea
 */
public class FramePrincipal extends javax.swing.JFrame {

    private ArrayList<Persona> listaPersonas = new ArrayList<Persona>();
    private String nombre, apellidos, dni, sexo, estado;
    private Dni nie = new Dni();

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        this.getContentPane().setBackground(Color.decode("#d9f7f7"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoCheckbox = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCheckBoxParo = new javax.swing.JCheckBox();
        jTextFieldDni = new javax.swing.JTextField();
        jCheckBoxEst = new javax.swing.JCheckBox();
        jCheckBoxTrab = new javax.swing.JCheckBox();
        jComboSexo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(255, 0, 0));
        setMaximumSize(new java.awt.Dimension(401, 351));
        setMinimumSize(new java.awt.Dimension(400, 370));
        setPreferredSize(new java.awt.Dimension(400, 370));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jTextFieldNombre.setText("Introduce nombre...");
        jTextFieldNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNombreMouseClicked(evt);
            }
        });
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 130, -1));

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 60, -1));

        jLabel2.setText("Apellidos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jTextFieldApellidos.setText("Introduce apellidos...");
        jTextFieldApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldApellidosMouseClicked(evt);
            }
        });
        getContentPane().add(jTextFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 130, -1));

        jLabel3.setText("DNI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        grupoCheckbox.add(jCheckBoxParo);
        jCheckBoxParo.setText("Paro");
        getContentPane().add(jCheckBoxParo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 70, -1));

        jTextFieldDni.setText("Introduce Dni...");
        jTextFieldDni.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jTextFieldDniComponentRemoved(evt);
            }
        });
        jTextFieldDni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldDniMouseClicked(evt);
            }
        });
        jTextFieldDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDniActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 130, -1));

        grupoCheckbox.add(jCheckBoxEst);
        jCheckBoxEst.setText("Estudiante");
        getContentPane().add(jCheckBoxEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        grupoCheckbox.add(jCheckBoxTrab);
        jCheckBoxTrab.setText("Trabajador");
        getContentPane().add(jCheckBoxTrab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jComboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona...", "Mujer", "Hombre" }));
        getContentPane().add(jComboSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 120, 20));

        jLabel4.setText("Sexo: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        jTextFieldNombre.setText("Introduce nombre...");
        jTextFieldApellidos.setText("Introduce apellidos...");
        jTextFieldDni.setText("Introduce Dni...");
        jComboSexo.setSelectedIndex(0);
        grupoCheckbox.clearSelection();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        try {
            // TODO add your handling code here:
            imprimirListaFichero();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        if (jTextFieldNombre.getText().isEmpty() || jTextFieldApellidos.getText().isEmpty() || jTextFieldDni.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Los campos estan vacios");
        } else {
            nombre = jTextFieldNombre.getText();
            apellidos = jTextFieldApellidos.getText();
            dni = jTextFieldDni.getText().toUpperCase();
            if (grupoCheckbox.getSelection() == null) {
                JOptionPane.showMessageDialog(this, "No has introducido el estado.");
            } else if (jCheckBoxParo.isSelected()) {
                estado = jCheckBoxParo.getText();
                seguir();
            } else if (jCheckBoxEst.isSelected()) {
                estado = jCheckBoxEst.getText();
                seguir();
            } else if (jCheckBoxTrab.isSelected()) {
                estado = jCheckBoxTrab.getText();
                seguir();
            }
        }

    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jTextFieldDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDniActionPerformed

    private void jTextFieldDniComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTextFieldDniComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDniComponentRemoved

    private void jTextFieldNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNombreMouseClicked
        // TODO add your handling code here:
        if (jTextFieldNombre.getText().contentEquals("Introduce nombre...")) {
            jTextFieldNombre.setText("");
        }
    }//GEN-LAST:event_jTextFieldNombreMouseClicked

    private void jTextFieldApellidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldApellidosMouseClicked
        // TODO add your handling code here:
        if (jTextFieldApellidos.getText().contentEquals("Introduce apellidos...")) {
            jTextFieldApellidos.setText("");
        }
    }//GEN-LAST:event_jTextFieldApellidosMouseClicked

    private void jTextFieldDniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldDniMouseClicked
        // TODO add your handling code here:
        if (jTextFieldDni.getText().contentEquals("Introduce Dni...")) {
            jTextFieldDni.setText("");
        }
    }//GEN-LAST:event_jTextFieldDniMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoCheckbox;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JCheckBox jCheckBoxEst;
    private javax.swing.JCheckBox jCheckBoxParo;
    private javax.swing.JCheckBox jCheckBoxTrab;
    private javax.swing.JComboBox<String> jComboSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables

    //Metodos
    private void seguir() {
        sexo = (String) jComboSexo.getSelectedItem();
        if (sexo.contentEquals("Selecciona...")) {
            JOptionPane.showMessageDialog(this, "No has seleccionado el sexo de la persona.");
        } else {
            if (!nie.validarNIF(dni)) {
                JOptionPane.showMessageDialog(this, "El DNI que ha ingresado no es valido.");
                jTextFieldDni.setText("");
            } else {
                nie.establecerNIF(dni);
                Persona p = new Persona(nombre, apellidos, nie, sexo, estado);
                listaPersonas.add(p);
                System.out.println(p);
            }
        }
    }
    
    private void imprimirListaFichero() throws FileNotFoundException{
        PrintWriter fichero = new PrintWriter(new FileOutputStream("src/EstatSolicitants.txt"));
        for (int k=0; k< listaPersonas.size();k++) {
            fichero.println(listaPersonas.get(k));
        }
        fichero.close();
    }
}
